### PR TITLE
Define nested_under_indifferent_access to return self

### PR DESCRIPTION
**Pull request by haileys**
This is required to make `TaintedHash` play nicely with `ActiveSupport::HashWithIndifferentAccess` on Rails 3.2, which calls `nested_under_indifferent_access` rather than `with_indifferent_access` on Hash subclasses.

cc @technoweenie @github/rails3

### CODE REVIEW

**Comment by bkeepers** [comment]
WTF Rails?

**Comment by haileys** [comment]
HashWithIndifferentAccess is such a crime.

**Comment by bkeepers** [comment]
But `params["user"]` is so much harder to type than `params[:user]` :trollface:

**Comment by technoweenie** [comment]
http://rubygems.org/gems/tainted_hash/versions/0.3.2

I can grant more people gem ownership if it helps.

**Pull request merged**
