### PR TITLE
Make the wrapper work in Rails3

### PR DESCRIPTION
**Pull request by r38y**
In Rails3, @_params is only set when params is called so it is nil by default. Using the params method returns something like a hash so there isn't an error. I don't know for sure but I think this will work in Rails2 as well.

### CODE REVIEW

**Comment by technoweenie** [comment]
I want to confirm this works on GitHub first... and I'm assuming you confirmed it works on Rails 3... :)

Also, here's the [Rails team's answer](https://github.com/rails/strong_parameters) to the issue.  I like the approach.  I had to go for Hash proxy because I didn't want to mess with overriding deep ActiveRecord methods.  I'm thinking of ripping the `#require` and `#permit` methods too.

**Comment by r38y** [comment]
I also want to change it to self.params= which I can do later tonight.

**Comment by r38y** [comment]
Alright, I switched it to the params setter to keep from accessing the underlying instance variables. I'm hoping this works in Rails 2? 

Also, best commit message EVAR https://github.com/rails/strong_parameters/commit/74dcb2f66cea0368bf6440725620057e78d6b346

**Comment by tmm1** [comment]
@r38y Are you using this successfully with rails3?

**Comment by r38y** [comment]
I'm not sure, I think I pretty quickly switched to strong_parameters after
that last comment and haven't looked back.

On Wed, Apr 17, 2013 at 10:13 PM, Aman Gupta notifications@github.comwrote:

> @r38y https://github.com/r38y Are you using this successfully with
> rails3?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/technoweenie/tainted_hash/pull/1#issuecomment-16549405
> .

## 

Randy Schmidt

**Comment by technoweenie** [comment]
Looks like we're moving to strong_parameters too.  :fire: this down.

**Pull request closed without merging**
